version: "3"
services:
  api:
    container_name: api
    image: 'zelejs/app-openjre11:latest'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./api:/webapps
    environment:
      TZ: "Asia/Shanghai"
      GREENFIELD: 'run'
    command:
      - /bin/sh
      - /usr/local/bin/run.sh
  mysqlserver:
    container_name: mysqlserver
    image: 'daocloud.io/library/mysql:5.7'
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_DATABASE: cinema
      MYSQL_ROOT_PASSWORD: rootAZaz@123
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d/sql_mode.cnf:/etc/mysql/conf.d/sql_mode.cnf
      - ./mysql/conf.d/utf8.cnf:/etc/mysql/conf.d/utf8.cnf


